trigger: none
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  path: build
- bash: ls -shal $(Agent.BuildDirectory)/build/challenge_b
- task: Docker@2
  inputs:
    containerRegistry: 'docker-ariyolo'
    repository: 'ariyolo/koin-backend'
    command: 'buildAndPush'
    Dockerfile: '$(Agent.BuildDirectory)/build/challenge_b/go/dockerfile'
    buildContext: '$(Agent.BuildDirectory)/build/challenge_b/go/'
