---
- name: Install Nginx web server
  package:
    name: nginx
    state: present

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload Nginx

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded